spring.application.name=studyparlour

# PostgreSQL Configuration
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# RSA Key Configuration for JWT
rsa.private-key=classpath:certs/private.pem
rsa.public-key=classpath:certs/public.pem

# JWT Settings
# 1hr expiry
jwt.expiration-ms=3600000